/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zarif
 */
public class user_statistics extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form user_statistics
     */
    String userid = "";

    public user_statistics(String user_id) {
        this.userid = user_id;
        initComponents();
        try {
            DefaultTableModel tblModel = new DefaultTableModel();
            tblModel = (DefaultTableModel) User_statistics.getModel();
            tblModel.setRowCount(0);
            
            DefaultTableModel tblModel2 = new DefaultTableModel();
            tblModel2 = (DefaultTableModel) User_statitsticschild.getModel();
            tblModel2.setRowCount(0);
            
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Zarif", "1967");
            Statement stmt = con.createStatement();

            rs = stmt.executeQuery("select * from answersheet where user_id='" + userid + "'");
            while (rs.next()) {

                int Id = Integer.valueOf(rs.getInt("id"));
                // String s=Integer.toString(Id);
                //String user = rs.getString("user_id");
                int tm = Integer.valueOf(rs.getInt("total_marks"));
                int um = Integer.valueOf(rs.getInt("user_marks"));
                String sd = rs.getString("submit_date");
                String tbdata[] = {String.valueOf(Id), String.valueOf(tm), String.valueOf(um), sd};

                tblModel.addRow(tbdata);

            }
            rs = stmt.executeQuery("select * from answersheetchild where answersheetid in (select id from answersheet where user_id='" + userid + "')");
            while (rs.next()) {

                int Id = Integer.valueOf(rs.getInt("id"));
                // String s=Integer.toString(Id);
                int exam_id = Integer.valueOf(rs.getInt("answersheetid"));               
                int question_id = Integer.valueOf(rs.getInt("question_id"));               
                int ans = Integer.valueOf(rs.getInt("answer"));
                int cans = Integer.valueOf(rs.getInt("canswer"));
                String tbdata[] = {String.valueOf(exam_id), String.valueOf(question_id), String.valueOf(ans), String.valueOf(cans)};

                tblModel2.addRow(tbdata);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        User_statistics = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        User_statitsticschild = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        User_statistics.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        User_statistics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "exam id", "total marks ", "user marks ", "submit date "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(User_statistics);

        User_statitsticschild.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        User_statitsticschild.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "exam id", "question no", "questionanswer ", "corrected answer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(User_statitsticschild);

        jLabel1.setText("Answer History");

        jLabel2.setText("Exam Record");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable User_statistics;
    private javax.swing.JTable User_statitsticschild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
